server:
  port: 8081
  servlet:
    context-path: /app1
spring:
  cloud:
    config:
      retry:
        initial-interval: 2000
        max-interval: 3000
        max-attempts: 10
        multiplier: 1.1
      fail-fast: true
  profiles:
    active: default,local
  application:
    name: app1
  config:
    import: optional:configserver:http://config-server:8080
