server:
  port: 8081
  servlet:
    context-path: /app1
spring:
  application:
    name: app1
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      retry:
        initial-interval: 2000
        max-interval: 3000
        max-attempts: 10
        multiplier: 1.1
      fail-fast: true
  config:
    import: optional:configserver:http://config-server:8080
  profiles:
    active:
      - default
      - local
  rabbitmq:
    host: rabbitmq-broker
    port: 5672
    username: guest
    password: guest
