app:
  name: config-server-demo
  description: This spring boot app demonstrates a spring cloud config server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Steve973/cloud-configs.git
          default-label: main
          search-paths: app1
          refresh-rate: 60
  rabbitmq:
    host: rabbitmq-broker
    port: 5672
    username: guest
    password: guest